name: TDM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2636
title: '#BecauseMusic'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#13a89e'
    - '#7dcdc7'
    - '#848689'
    - '#d3eae9'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
