name: TDM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2636
title: '#BecauseMusic'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#323232'
    - '#4d4d4d'
    - '#ababab'
    - '#878787'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
